let token='',offset=0,busy=false;const $=id=>document.getElementById(id);let generation=0;
async function load(){if(busy)return;busy=true;const run=++generation;$('status').textContent='Загрузка…';$('submissions').replaceChildren();try{const r=await window.terminalFetch('/api/admin/submissions?offset='+offset,{headers:{Authorization:'Bearer '+token},cache:'no-store'});const body=await r.json();if(!r.ok)throw new Error(body.error||'Ошибка загрузки');if(run!==generation)return;$('login').hidden=true;$('dashboard').hidden=false;$('key').value='';$('status').textContent=body.items.length?'Получено записей на странице: '+body.items.length:'На этой странице пока нет отправок.';body.items.forEach(row=>{const item=document.createElement('details');const summary=document.createElement('summary');summary.textContent=new Date(row.created_at).toLocaleString()+' · '+row.test_code+' · Сотрудник '+row.employee_number;const info=document.createElement('p');info.textContent='Идентификационный код: '+row.identification_code+' | '+(row.mode==='preview'?'Предварительный просмотр — без оценки':'Баллы: '+row.score+' / '+row.total);const receipt=document.createElement('p');receipt.textContent='Номер отправки: '+row.id;const list=document.createElement('ol');row.answers.forEach(a=>{const li=document.createElement('li');const question=document.createElement('strong');question.textContent=a.question;if(a.context){const context=document.createElement('p');context.textContent=a.context;context.style.whiteSpace='pre-line';li.append(context);}const answer=document.createElement('p');answer.textContent='Ответ: '+['А','Б','В','Г','Д'][a.selected]+' — '+a.selectedText;li.prepend(question);li.append(answer);if(typeof a.isCorrect==='boolean'){const verdict=document.createElement('p');verdict.textContent=a.isCorrect?'✓ Верно':'✕ Неверно';verdict.style.color=a.isCorrect?'#abd9ed':'#e5c17d';li.append(verdict);}list.append(li);});item.append(summary,info,receipt,list);if(row.retake_locked){const allow=document.createElement('button');allow.textContent='РАЗРЕШИТЬ ОДНУ ПОВТОРНУЮ ПОПЫТКУ';allow.onclick=async()=>{allow.disabled=true;try{const response=await window.terminalFetch('/api/admin/retakes',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({submissionId:row.id})});const result=await response.json();if(!response.ok)throw Error(result.error);allow.textContent='ПОВТОРНАЯ ПОПЫТКА РАЗРЕШЕНА';}catch(error){allow.disabled=false;$('status').textContent=error.message;}};item.append(allow);}$('submissions').append(item);});$('previous').disabled=offset===0;$('next').disabled=!body.hasMore;$('page').textContent='Страница '+(offset/25+1);}catch(e){if(run!==generation)return;$('status').textContent=e.message;$('dashboard').hidden=true;$('login').hidden=false;}finally{busy=false;}}
$('login').onsubmit=e=>{e.preventDefault();token=$('key').value;offset=0;load();};$('refresh').onclick=load;$('next').onclick=()=>{if(!busy){offset+=25;load();}};$('previous').onclick=()=>{if(!busy){offset=Math.max(0,offset-25);load();}};$('logout').onclick=()=>{generation++;token='';$('generated-access-key').value='';$('access-key-result').hidden=true;$('access-key-status').textContent='';$('key').value='';$('submissions').replaceChildren();$('dashboard').hidden=true;$('login').hidden=false;$('status').textContent='Вы вышли из кабинета.';};

$('create-access-key').onclick=async()=>{
 const run=generation;$('create-access-key').disabled=true;$('access-key-status').textContent='Создание ключа…';$('access-key-result').hidden=true;$('generated-access-key').value='';
 try{const response=await window.terminalFetch('/api/admin/access-keys',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({testCode:$('key-test').value}),signal:AbortSignal.timeout(15000)});const result=await response.json();if(run!==generation)return;if(!response.ok)throw Error(result.error||'Не удалось создать ключ.');$('generated-access-key').value=result.key;$('access-key-expiry').textContent='Можно начать тест до '+new Date(result.expiresAt).toLocaleString()+'. Начатый тест можно завершить в течение 24 часов.';$('access-key-result').hidden=false;$('access-key-status').textContent='Передайте ключ участникам. Сохраните его сейчас: после выхода он не отображается.';}catch(error){if(run===generation)$('access-key-status').textContent=error.message;}finally{$('create-access-key').disabled=false;}
};
$('copy-access-key').onclick=async()=>{try{await navigator.clipboard.writeText($('generated-access-key').value);$('access-key-status').textContent='Ключ скопирован.';}catch{$('generated-access-key').select();$('access-key-status').textContent='Нажмите Ctrl+C, чтобы скопировать ключ.';}};
